CREATE TABLE patient_visits (
    appointment_id INT AUTO_INCREMENT,
    visit_date DATE NOT NULL,
    visit_time TIME NOT NULL,
    reason_for_visit VARCHAR(255),
    symptoms VARCHAR(255),
    diagnosis VARCHAR(255),
    treatment VARCHAR(255),
    email VARCHAR(255),
    provider_name VARCHAR(255),
    provider_contact VARCHAR(255),
    medication_name VARCHAR(255),
    medication_dosage VARCHAR(255),
    medication_frequency VARCHAR(255),
    medication_duration VARCHAR(255),
    lab_test_name VARCHAR(255),
    lab_test_results VARCHAR(255),
    insurance_code VARCHAR(255),
    billing_code VARCHAR(255),
    total_cost DECIMAL(10,2),
    follow_up_instructions VARCHAR(255),
    notification_setting VARCHAR(255),
    PRIMARY KEY (appointment_id)
);